language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=postgres
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database vanilla_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rspec ./spec
